# Generated by Django 5.1.4 on 2024-12-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=+998901112233, unique=True),
            preserve_default=False,
        ),
    ]
