# Generated by Django 5.1.4 on 2024-12-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='no@email.com', max_length=254, null=True, unique=True),
        ),
    ]
